server:
  port: 80
  
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    password: 11
    username: 11
    url: jdbc:oracle:thin:@10.10.100.000:1521:orcl
    platform: hikari
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/*/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.*.entity,com.*.entity.*
  global-config:
    #是否缓存 Sql 解析，默认不缓存。
    sql-parser-cache: true
    db-config:
      #主键类型
      id-type: id-worker 
      #字段策略
      field-strategy: not-empty      
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: oracle
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId） 
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null' 